apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment
  labels:
    app: dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "otel-autoinstrumentation"
    spec:
      containers:
      - name: dotnet-app
        image: ghcr.io/practical-otel/dotnet-plain-for-k8s-workshop:latest
        ports:
        - containerPort: 8080