apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-coded-deployment
  labels:
    app: dotnet-app-coded
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app-coded
  template:
    metadata:
      labels:
        app: dotnet-app-coded
    spec:
      containers:
      - name: dotnet-app
        image: ghcr.io/practical-otel/dotnet-coded-instrumentation-for-k8s-workshop:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(OTEL_NODE_IP):4317"
